config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:new]
  get '/signup', to: 'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  put '/users/:id/approve', to: 'users#approve', as: 'approve'

  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
  get '/uploading', to: 'static_pages#uploading'

  resources :stories

  patch '/stories/:id/feature', to: 'stories#feature', as: 'feature'

  patch '/stories/:id/story_approve', to: 'stories#story_approve', as: 'story_approve'

  resources :sections

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 100}

  validates :password, presence: true, confirmation: true, length: {minimum: 6}, allow_nil: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: true

  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :approve]
  before_action :user_security
  before_action :approved_user_security, only: [:approve]
  before_action :current_user_security, only: [:edit, :update]
  before_action :current_user_or_approved_user_security, only: [:destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /signup
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "#{@user.name} was successfully created"
      redirect_to @user
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      flash[:success] = "#{@user.name} was successfully updated"
      redirect_to @user
    else
      render :edit
    end
  end

  # PATCH/UPDATE /users/1/approve
  def approve
    if @user.approved
      @user.approved = false
      string = 'unsapproved'
    else
      @user.approved = true
      string = 'approved'
    end

    if @user.save!
      flash.now[:success] = "#{@user.name} was successfully #{string}."
      redirect_to users_path
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name} was deleted."
    redirect_to users_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:email, :name, :approved, :password, :password_confirmation)
    end

    def current_user_security
      @user = User.find(params[:id])
      if @user != current_user
        flash.now[:danger] = @@security_message
        redirect_to root_path
      end
    end

    def current_user_or_approved_user_security
      if current_user != @user || !user.approved
        flash.now[:danger] = @@security_message
        redirect_to root_path
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
    <% if user.errors.any? %>
        <div id="error_explanation">
          <h2>There were <%= pluralize(user.errors.count, "error") %> with this form.</h2>
          <ul>
            <% user.errors.full_messages.each do |message| %>
                <li><%= message %>.</li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-outer">
      <div class="field">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>

      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>

      <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>

      <div class="field">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
      </div>

      <div class="actions">
        <%= f.submit class: "button" %> or <%= link_to 'go back', users_path, style: 'font-size: 18px' %>
      </div>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1 id="main-header">editing <%= @user.name %></h1>
<hr>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1 id="large-header">Users</h1>
<hr>

<div class="content">
  <table class="users-table">
    <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Approved</th>
      <th colspan="4"></th>
    </tr>
    </thead>

    <tbody>
    <% @users.each do |user| %>
        <tr id="<%= "user-#{user.id}" %>">
          <td id="<%= "user-#{user.id}-email" %>"><%= user.email %></td>
          <td id="<%= "user-#{user.id}-name" %>"><%= user.name %></td>
          <td id="<%= "user-#{user.id}-approved" %>"><%= user.approved ? "true" : "false" %></td>
          <td><%= link_to 'Show', user, class: 'button' %></td>
          <td><%= link_to 'Edit', edit_user_path(user), class: 'button' %></td>
          <% if  current_user.approved %>
              <td>
                <% if !user.approved %>
                    <%= link_to('Approve', approve_path(user), method: :put, data: { confirm: 'Are you sure?' }, class: 'button') %>
                <% else %>
                    <%= link_to('Unapprove', approve_path(user), method: :put, data: { confirm: 'Are you sure?' }, class: 'button') %>
                <% end %>
              </td>
          <% end %>
          <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button' %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New User', signup_path, class: 'button' %>
</div>

app/views/users/new.html.erb
<h1 id="main-header">new user</h1>
<hr>

<%= render 'form', user: @user %>

<aside>Any new users will need to be approved. This feature is only for Ellipses members.</aside>

app/views/users/show.html.erb
<h1 id="large-header"><%= @user.name %></h1>
<hr>

<div class="content">
  <p>
    <strong>Email</strong>
    <%= @user.email %>
  </p>

  <p>
    <strong>Name</strong>
    <%= @user.name %>
  </p>

  <p style="margin-bottom: 20px;">
    <strong>Approved</strong>
    <%= @user.approved ? "true" : "false" %>
  </p>

  <%= link_to 'Edit', edit_user_path(@user), class: "button" %>
  <%= link_to 'Back', users_path, class: "button" %>
</div>