config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:new]
  get '/signup', to: 'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  put '/users/:id/approve', to: 'users#approve', as: 'approve'

  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
  get '/uploading', to: 'static_pages#uploading'

  resources :stories

  patch '/stories/:id/feature', to: 'stories#feature', as: 'feature'

  patch '/stories/:id/story_approve', to: 'stories#story_approve', as: 'story_approve'

  resources :sections

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/story.rb
class Story < ApplicationRecord
  validates :title, presence: true, length: {maximum: 200}
  validates :author, presence: true, length: {maximum: 100}
  validates :genre, presence: true, length: {maximum: 100}
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, length: {maximum: 255}

  class ImagesValidator < ActiveModel::Validator
    def validate(record)
      if record.images.empty? and record.content.empty? and record.section.name == 'art'
        images.errors << 'need at least one image or some content for art submissions'
      end
    end
  end
  validates_with ImagesValidator

  belongs_to :section
  has_many :images, dependent: :delete_all

  extend FriendlyId
  friendly_id :title, use: :slugged

  def content_to_html
    self.content.gsub(/\n/, '</p><p>')
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy, :story_approve]
  attr_accessor :featured

  def show
    @story = Story.friendly.find(params[:id])
    @content = @story.content_to_html
  end

  def edit
    @story = Story.friendly.find(params[:id])
  end

  def update
    @story = Story.friendly.find(params[:id])
    if @story.update_attributes(story_params)
      flash[:success] = "\"#{@story.title}\" was successfully updated."
      redirect_to @story
    else
      render 'edit'
    end
  end

  def story_approve
    @story = Story.friendly.find(params[:id])
    if @story.story_approved
      @story.story_approved = false
      string = 'disapproved'
    else
      @story.story_approved = true
      string = 'approved'
    end

    if @story.save!
      flash.now[:success] = "#{@story.title} was successfully #{string}."
      redirect_to @story
    end
  end

  def destroy
    @section = Story.friendly.find(params[:id]).section
    Story.friendly.find(params[:id]).destroy
    flash[:success] = "Story deleted."
    redirect_to @section
  end

  def feature
    @story = Story.friendly.find(params[:id])
    @prev_featured = @story.section.stories.find_by(featured: true)

    if @prev_featured
      @prev_featured.featured = false
      @prev_featured.save!
    end

    @story.featured = true

    if @story.save
      flash[:success] = "\"#{@story.title}\" is now featured."
      redirect_to root_url
    else
      flash[:danger] = "Something went wrong."
      redirect_to @story.section
    end
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)
    @story.featured = false

    if params[:story][:images]
      params[:story][:images].each do |image|
        @story.images.new(image: image)
      end
    end

    if @story.save
      flash[:success] = "\"#{@story.title}\" was successfully submitted"
      redirect_to @story
    else
      render :new
    end
  end

  private
  def story_params
    params.require(:story).permit(:title, :author, :content, :genre, :section_id, :anonymous, :comments, :email, :story_approved, :featured, :images, :gallery_layout)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in to do this."
      redirect_to login_url
    end
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/edit.html.erb
<h1 id="main-header">edit <%= @story.title %></h1>
<hr>

<%= form_for(@story) do |f| %>
    <% if @story.errors.any? %>
        <div id="error_explanation">
          <h2>There were <%= pluralize(@story.errors.count, "error") %> with this form.</h2>
          <ul>
            <% @story.errors.full_messages.each do |message| %>
                <li><%= message %>.</li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-outer">
      <div class="field">
        <%= f.label :section_id, "Section type" %>
        <%= f.select(:section_id, options_for_select([["Short Stories", 1], ["Poetry", 2], ["Art", 3]], @story.section_id)) %>
      </div>

      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, maxlength: 200 %>
        <p class="sublabel">Editing the title will not change the url.</p>
      </div>

      <div class="field">
        <%= f.label :author %>
        <%= f.text_field :author, maxlength: 100 %>
      </div>

      <div class="field">
        <%= f.label :email %>
        <%= f.text_field :email, maxlength: 255 %>
      </div>

      <div class="field">
        <%= f.label :anonymous, "Keep story anonymous" %>
        <%= f.check_box :anonymous, class: "pretty-checkbox" %>
      </div>

      <div class="field">
        <%= f.label :genre %>
        <%= f.text_field :genre, maxlength: 100 %>
      </div>

      <div class="field">
        <%= f.label :content %>
        <%= f.text_area :content, class: "tinymce" %>
        <%= tinymce %>
        <p class="sublabel" style="margin-top: 0.2em !important">Use <%= link_to "this guide", uploading_path, target: "_blank" %> for adding any images.</p>
      </div>

      <!-- <div class="field art-field hidden">
        <%= f.label :images, "Upload images", class: "file-upload button" %>
        <%= f.file_field(:images, multiple: true, accept:'image/*', class: " file-button") %>
      </div> -->

      <div class="field">
        <%= f.label :gallery_layout, "Use gallery layout" %>
        <%= f.check_box :gallery_layout, class: "pretty-checkbox" %>
        <p class="sublabel">If this checkbox isn't marked, any images in your story will take up the entire width of the screen.</p>
        <p class="sublabel">If it is marked, please be sure your images are high resolution (width should be 1000px or more).</p>
      </div>

      <div class="field">
        <%= f.label :comments %>
        <%= f.text_area :comments, class: "comments" %>
      </div>

      <% if current_user %>

        <div class="field">
          <%= f.label :story_approved, "Approved?" %>
          <%= f.check_box :story_approved, class: "pretty-checkbox" %>
        </div>
      <% end %>

      <div class="actions">
        <%= f.submit "Update story", class: "button" %>
      </div>
    </div>
<% end %>


<aside>All submissions will not publicly appear until they are approved.</aside>

app/views/stories/new.html.erb
<h1 id="main-header">submit a story</h1>
<hr>

<%= form_for(@story) do |f| %>
    <% if @story.errors.any? %>
        <div id="error_explanation">
          <h2>There were <%= pluralize(@story.errors.count, "error") %> with this form.</h2>
          <ul>
            <% @story.errors.full_messages.each do |message| %>
                <li><%= message %>.</li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-outer">
      <div class="field">
        <%= f.label :section_id, "Submission type" %>
        <%= f.select(:section_id, options_for_select([["Short Stories", 1], ["Poetry", 2], ["Art", 3]])) %>
      </div>

      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, maxlength: 200 %>
      </div>

      <div class="field">
        <%= f.label :author %>
        <%= f.text_field :author, maxlength: 100 %>
        <p class="sublabel">Please enter your full name, even if you would like to submit the story anonymously.</p>
      </div>

      <div class="field">
        <%= f.label :email %>
        <%= f.text_field :email, maxlength: 255 %>
        <p class="sublabel">Use an email that you check regularly that Ellipses can contact you with.</p>
      </div>

      <div class="field">
        <%= f.label :anonymous, "Keep story anonymous" %>
        <%= f.check_box :anonymous, class: "pretty-checkbox" %>
        <p class="sublabel">Mark this checkbox if you would like your name to not be publicly displayed.</p>
      </div>

      <div class="field">
        <%= f.label :genre %>
        <%= f.text_field :genre, maxlength: 100 %>
        <p class="sublabel">If you are confused about your story's genre, an Ellipses member can edit it later.</p>
      </div>

      <div class="field story-field">
        <%= f.label :content %>
        <%= f.text_area :content, class: "tinymce" %>
        <%= tinymce %>
        <p class="sublabel" style="margin-top: 0.2em !important">Use <%= link_to "this guide", uploading_path, target: "_blank" %> for adding any images.</p>
      </div>

      <!-- <div class="field art-field hidden">
        <%= f.label :images, "Upload images", class: "file-upload button" %>
        <%= f.file_field(:images, multiple: true, accept:'image/*', class: " file-button") %>
        <p class="sublabel">After submission, you cannot add any additional images. Images will be ordered by date.
      </div> -->

      <div class="field">
        <%= f.label :gallery_layout, "Use gallery layout" %>
        <%= f.check_box :gallery_layout, class: "pretty-checkbox", checked: true %>
        <p class="sublabel">If this checkbox isn't marked, any images in your story will take up the entire width of the screen.</p>
        <p class="sublabel">If it is marked, please be sure your images are high resolution (width should be 1000px or more).</p>
      </div>

      <div class="field">
        <%= f.label :comments %>
        <%= f.text_area :comments, class: "comments" %>
        <p class="sublabel">Put any anything else Ellipses should know here. This box is optional and will not be publicly visible.<p>
      </div>

      <div class="actions">
        <%= f.submit "Submit story", class: "button" %>
        <p class="sublabel" style="margin-top: 0 !important">You will not be able to edit your submission after clicking this button without <%= mail_to "ellipseslitmag@gmail.com", "contacting Ellipses" %>.</p>
      </div>
    </div>
<% end %>


<aside>All submissions will not publicly appear until they are approved.</aside>

app/views/stories/show.html.erb
<% if logged_in? %>
  <div class="admin-box-outer" style="transform: translateY(1em);">
    <h1>Admin Box</h1>
    <p style="font-weight: 100; font-size: 0.8em">This section is not visible to normal users.</p>
    <p><span>Full name:</span> <%= @story.author %></p>
    <p><span>Email:</span> <%= @story.email %></p>
    <p><span>Comments:</span> <%= @story.comments %></p>
    <p>This story is currently <strong><%= @story.story_approved ? "approved" : "not approved" %></strong>.</p>
    <%= link_to "Edit this story", edit_story_path(@story), class: "button" %>
    <%= link_to "Delete this story", @story, method: :delete, data:
                                    {confirm: "Are you sure you want to delete #{@story.title}? This action is not undoable."}, class: "button" %>
    <%= link_to "Feature", feature_path(@story), method: :patch, data:
                                    {confirm: "Are you sure you want to feature #{@story.title}? This will remove the currently featured story."}, class: "button" %>
    <% if !@story.story_approved %>
      <%= link_to "Approve", story_approve_path(@story), method: :patch, data:
                                      {confirm: "Are you sure you want to approve #{@story.title}?"}, class: "button" %>
    <% end %>
  </div>
<% end %>
<div class="story-content-outer content-<%= @story.section.name.split(" ")[0] %>">
  <div class="story-header header-<%= @story.section.name.split(" ")[0] %>">
    <h1 class="story-title hidden"><%= @story.title %></h1>
    <h3 class="story-title hidden">by <%= @story.anonymous ? "Anonymous" : @story.author %><%= link_to "<< back to #{@story.section.name}", @story.section%></h3>
    <!-- <%= link_to "<<a #{@story.section.name}", @story.section, class: "back-link" %> -->
  </div>
  <hr>
  <% if @story.story_approved == false %>
    <h2 style="margin: 0 !important">This story is currently <span style="font-weight: 900; text-decoration: underline">not</span> approved.</h2>
    <p style="margin: 0 !important">This story was submitted into the <span style="font-weight: 900"><%= @story.section.name %></span> section. If you feel the approval process is taking too long or something is off with your submission's format, you can contact <%= mail_to("ellipseslitmag@gmail.com", "Ellipses here") %>.</p>
  <% end %>
  <div class="inner-content hidden gallery-<%= @story.gallery_layout ? true : false %>">
    <p><%= @content.html_safe %></p>
    <% if @story.section.name == "art" && @story.images.any? %>
      <% @story.images.each do |image| %>
        <a href="<%= image.image.url %>" class="fancybox">
          <%= image_tag image.image.url, class: "story-img" %>
        </a>
      <% end %>
    <% end %>
  </div>
</div>