config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:new]
  get '/signup', to: 'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  put '/users/:id/approve', to: 'users#approve', as: 'approve'

  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
  get '/uploading', to: 'static_pages#uploading'

  resources :stories

  patch '/stories/:id/feature', to: 'stories#feature', as: 'feature'

  patch '/stories/:id/story_approve', to: 'stories#story_approve', as: 'story_approve'

  resources :sections

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ellipses literary magazine</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tinymce_assets %>
  </head>

  <body>
    <div id="everything-outer">
      <div id="header-outer">
        <a href="/"><%= image_tag "logo-thin-header.png", class: "logo-header" %></a>
        <div class="vertical-hr"></div>
        <%= link_to "ellipses", root_path, id: "header-name" %>
        <div id="hamburger">
          <div>
            <div class="ham1"></div>
            <div class="ham2"></div>
            <div class="ham3"></div>
          </div>
        </div>
        <div id="header-links">
          <%= link_to "short stories", '/sections/short-stories' %>
          <%= link_to "poetry", '/sections/poetry' %>
          <%= link_to "art", '/sections/art' %>
          <% if logged_in? %>
            <%= link_to "users", users_path %>
            <%= link_to "log out", logout_path, method: :delete, style: "z-index: 100" %>
          <% else %>
            <%= link_to "submit", new_story_path %>
            <%= link_to "sign in", login_path, style: "z-index: 100" %>
          <% end %>
        </div>
      </div>
      <div id="content-outer">
        <% flash.each do |message_type, message| %>
          <div class="flash flash-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
        <h1 id="bottom-ellipses">...</h1>
      </div>
      <div id="footer-outer">
        <div id="footer-info">
          <p>&copy; Ellipses Lit Magazine <%= Time.now.year %></p>
          <%= mail_to "ellipseslitmag@gmail.com", "contact Ellipses" %>
          <%= mail_to "noahfiner@gmail.com,durbhasaketram@gmail.com", "contact the webmaster" %>
        </div>
        <div id="footer-links">
          <%= link_to "short stories", '/sections/short-stories' %>
          <%= link_to "poetry", '/sections/poetry' %>
          <%= link_to "art", '/sections/art' %>
          <%= link_to "about", about_path %>
        </div>
      </div>
    </div>
  </body>
</html>